name: test_env_cmip6_preprocessing
channels:
  - conda-forge
dependencies:
  - xarray>=0.17.0
  - pandas<1.3 # remove this once https://github.com/pydata/xarray/issues/5581 is released
  - netcdf4
  - scipy
  - xgcm
  - cftime
  - regionmask
  - cartopy
  - xesmf
  - xarrayutils
  - pint
  - cf_xarray>=0.6.0
#   - pint-xarray #waiting for v0.2.1 to be released on conda-forge
  - pytest-cov
  - pytest-xdist
  - codecov
  - pip
  - pip:
    - pint-xarray # just temporary (see above)
