name: test_env_cmip6_preprocessing
channels:
  - conda-forge
dependencies:
  - xarray
  - xgcm
  # Dependencies for the pangeo cloud data
  - intake-esm
  - gcsfs
  - zarr
  - pint
  - cf_xarray>=0.6.0
#   - pint-xarray # Waiting for release of v0.2.1 on conda-forge
  # Dependencies for the testing suite
  - pytest-cov
  - pytest-xdist
  - pytest-rerunfailures
  - codecov
  - pip
  - pip:
    - pint-xarray # ! temporary, see above
