name: cmip6_preprocessing_docs
channels:
  - conda-forge
dependencies:
  - python
  - xarray
  - xgcm
  - pyproj
  - cftime
  - matplotlib
  - regionmask
  - pytest-cov
  - pytest-xdist
  - codecov
  # Insert your dependencies here
  - numpydoc
  - sphinx
  - ipython
  - pandoc
  - recommonmark
  - pip
  - pip:
    - nbsphinx
    - jupyter_client
    - sphinx_pangeo_theme
    - sphinx-copybutton
    - sphinxcontrib-srclinks
